Audio clip module
Unity-Technologies/ProjectAuditor pull request #112
Opened 2022-08-29 20:34 UTC by JJJianJiao

Please review my AudioClip Module task.

Thanks

2022-08-29 20:37 UTC, JJJianJiao reviewed
Please review my task. Thanks

2022-08-29 21:22 UTC, justinkiffiak-SM reviewed
Look Good. No comments or observations for fixes/tweaks.
Just the Documentation page to add and it's set. :)

2022-08-30 21:10 UTC, justinkiffiak-SM reviewed
Seems good.

2022-09-06 10:13 UTC, mtrive requested changes

2022-09-06 17:40 UTC, JJJianJiao commented on Editor/Modules/AudioClipModule.cs
> +                    Path.GetExtension(path).Substring(1),
Here I try to get the file name. The AudioCompressionFormat is not a file name.

2022-09-06 17:48 UTC, JJJianJiao commented on Editor/Modules/AudioClipModule.cs
> +                    importer.defaultSampleSettings.loadType,
![image](https://user-images.githubusercontent.com/108890606/188704478-6f19476b-416c-4d95-b1c5-b6ceead4e9f2.png)
I did not see any platform-specific sampleSettings.

2022-09-06 18:03 UTC, JJJianJiao commented on Editor/Modules/AudioClipModule.cs
> +                    importer.preloadAudioData,
![image](https://user-images.githubusercontent.com/108890606/188706845-c27ee139-28a6-47ac-ad40-38a2d894f540.png)
This is version 2022.1. I did not see the AudioImporter.SampleSettings. The preloadAudioData is still there as a property in AudioImporter.

2022-09-06 18:38 UTC, mtrive commented on Editor/Modules/AudioClipModule.cs
> +                    importer.preloadAudioData,
> This is version 2022.1. I did not see the AudioImporter.SampleSettings. The preloadAudioData is still there as a property in AudioImporter.

Have you tried with 2022.2?

2022-09-06 18:39 UTC, mtrive commented on Editor/Modules/AudioClipModule.cs
> +                    importer.defaultSampleSettings.loadType,
have you tried to get the _AudioImporterSampleSettings_ with _GetOverrideSampleSettings_ ?

2022-09-06 18:42 UTC, JJJianJiao commented on Editor/Modules/AudioClipModule.cs
> +                    importer.preloadAudioData,
Sorry. I tried 2022.2. It does be removed to SampleSettings. In the beginning, I thought it started from 2020.1. My bad.

2022-09-09 18:25 UTC, JJJianJiao commented on Editor/Modules/AudioClipModule.cs
> +                    importer.defaultSampleSettings.loadType,
yes. It works. Thanks
![image](https://user-images.githubusercontent.com/108890606/189418975-235a669e-671a-4dca-8e4e-dab50272ed18.png)
![image](https://user-images.githubusercontent.com/108890606/189419017-bedd17cf-b15d-4c3c-a0a6-3298fd65621d.png)

2022-09-09 18:33 UTC, JJJianJiao commented on Editor/Modules/AudioClipModule.cs
> +                    importer.defaultSampleSettings.loadType,
just wonder, because this is in the project auditor, should we use the hard code here?

2022-09-09 18:36 UTC, JJJianJiao commented on Editor/Modules/AudioClipModule.cs
> +                    importer.defaultSampleSettings.loadType,
I see the ProjectAuditorParams has stored the platform, should we use the platform?

2022-09-12 08:47 UTC, mtrive commented on Editor/Modules/AudioClipModule.cs
> +                    importer.GetOverrideSampleSettings(platform.ToString()).preloadAudioData,
could you please use `importer.GetOverrideSampleSettings(platform.ToString())` only once and store the result into a `var` please?

2022-09-12 08:48 UTC, mtrive commented on Editor/UI/ProjectAuditorAnalytics.cs
> +                    return "audio-clip";
For constestency, this should be 'audio_clip, not 'audio-clip',

2022-09-12 08:53 UTC, mtrive commented on Editor/UI/ProjectAuditorWindow.cs
> +                    menuLabel = "Experimental/AudioClip",
_Experimental/AudioClip_ => _Experimental/Audio Clips_ for consistency

2022-09-12 09:10 UTC, mtrive commented on Editor/UI/ProjectAuditorWindow.cs
>                  ViewDescriptor.Register(new ViewDescriptor
please add filters via _showFilters_ so it's possible to search

2022-09-12 09:17 UTC, mtrive requested changes
Seems to work pretty well, I just made a few comments.

2022-09-19 08:39 UTC, mtrive approved these changes
Looks good! Just two minor comments.

2022-09-19 08:39 UTC, mtrive commented on Editor/Modules/AudioClipModule.cs
> +        public override bool isEnabledByDefault => false;
could you please move this up, below the 'name' property override?

2022-09-19 08:39 UTC, mtrive commented on Editor/Modules/AudioClipModule.cs
> +        private void AnalyzeAudioClip(List<ProjectIssue> issues, BuildTarget platform)
please remove `private`

2022-09-19 15:03 UTC, merged