Package diagnostics
Unity-Technologies/ProjectAuditor pull request #114
Opened 2022-09-01 18:59 UTC by JJJianJiao

I finish the Package-Diagnostics task.

Please review my work. 

Thanks very much!

PS: I feel confused with the Experimental and Preview in unity. I need to discuss this with Marco later.

2022-09-01 20:01 UTC, justinkiffiak-SM reviewed
Nice Work. Just a tweak or two regarding spelling, along with Unit Tests, and page created in Documentation ( manual ).

2022-09-01 21:09 UTC, justinkiffiak-SM reviewed
Looks great, now onto the Unit Tests and Documentation page.

2022-09-06 10:04 UTC, mtrive requested changes

2022-09-06 10:04 UTC, mtrive commented on Editor/UI/ProjectAuditorWindow.cs
> +                    analyticsEvent = (int)ProjectAuditorAnalytics.UIButton.Packages
this should be _PackageVersion_

2022-09-06 10:15 UTC, mtrive commented on Editor/Modules/PackagesModule.cs
> +                new PropertyDefinition { type = PropertyType.Description, name = "Display Name"},
let's rename to _Name_

2022-09-06 10:17 UTC, mtrive commented on Editor/Modules/PackagesModule.cs
> +                new PropertyDefinition { type = PropertyTypeUtil.FromCustom(PackageVersionProperty.Name), format = PropertyFormat.String, name = "Package Name", defaultGroup = true},
let's use _Id_ and _Package Id_ for _name_  and _longName_ respectively

2022-09-06 17:05 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ProjectAuditor?pullRequest=114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ProjectAuditor?pullRequest=114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/ProjectAuditor?pullRequest=114) it.</sub>

2022-09-06 18:42 UTC, mtrive commented on Editor/UI/ProjectAuditorWindow.cs
> +                    analyticsEvent = (int)ProjectAuditorAnalytics.UIButton.Packages
Have you changed this to use ProjectAuditorAnalytics.UIButton.PackageVersion ?

2022-09-06 19:31 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ProjectAuditor?pullRequest=114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/ProjectAuditor?pullRequest=114) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/ProjectAuditor?pullRequest=114) it.</sub>

2022-09-06 20:04 UTC, closed without merging