Shader improvements
Unity-Technologies/ProjectAuditor pull request #124
Opened 2022-09-27 13:42 UTC by mtrive

Shaders improvements:
- Add "Num Variants" property to reported shaders
- Add Compute Shader Variants support

2022-09-29 11:31 UTC, cinight approved these changes
lgtm! Thanks for adding this.

2022-10-03 22:21 UTC, unitystevem requested changes
As discussed, I think ShaderTypeIsFragment() needs a comment explaining the context around why it does what it does with OpenGL/ES shaders.

More seriously, I'm seeing a divide by 0 exception on line 411 of ShadersModule.cs. I guess (numCompilerPlatforms == 0) for some shaders? Error message and partial callstack below. Repro steps are:

- Add this branch of PA to a new project with the LEGO Microgame, 2021.3.7f1
- Open Project Auditor, go to Shader Variants window, click Clear
- Build the game (I build OSX Standalone)
- In the Shader Variants window, click Refresh.

------

DivideByZeroException: Attempted to divide by zero.
Unity.ProjectAuditor.Editor.Modules.ShadersModule.AddShader (UnityEngine.Shader shader, System.String assetPath, System.String assetSize, System.Boolean isAlwaysIncluded, System.Action`1[T] onIssueFound) (at Library/PackageCache/com.unity.project-auditor@c73131f0c1/Editor/Modules/ShadersModule.cs:411)
Unity.ProjectAuditor.Editor.Modules.ShadersModule.ProcessShaders (System.Collections.Generic.Dictionary`2[TKey,TValue] shaderPathMap, System.Action`1[T] onIncomingIssues) (at Library/PackageCache/com.unity.project-auditor@c73131f0c1/Editor/Modules/ShadersModule.cs:368)
Unity.ProjectAuditor.Editor.Modules.ShadersModule.Audit (Unity.ProjectAuditor.Editor.ProjectAuditorParams projectAuditorParams, Unity.ProjectAuditor.Editor.IProgress progress) (at Library/PackageCache/com.unity.project-auditor@c73131f0c1/Editor/Modules/ShadersModule.cs:248)
Unity.ProjectAuditor.Editor.UI.ProjectAuditorWindow.AuditSingleModule (Unity.ProjectAuditor.Editor.Core.ProjectAuditorModule module) (at Library/PackageCache/com.unity.project-auditor@c73131f0c1/Editor/UI/ProjectAuditorWindow.cs:675)
Unity.ProjectAuditor.Editor.UI.ProjectAuditorWindow.AuditSingleModule[T] () (at Library/PackageCache/com.unity.project-auditor@c73131f0c1/Editor/UI/ProjectAuditorWindow.cs:634)
Unity.ProjectAuditor.Editor.UI.ProjectAuditorWindow.AnalyzeShaderVariants () (at Library/PackageCache/com.unity.project-auditor@c73131f0c1/Editor/UI/ProjectAuditorWindow.cs:680)
Unity.ProjectAuditor.Editor.UI.ProjectAuditorWindow+<>c.<OnLoad>b__32_9 () (at Library/PackageCache/com.unity.project-auditor@c73131f0c1/Editor/UI/ProjectAuditorWindow.cs:341)
Unity.ProjectAuditor.Editor.UI.Framework.AnalysisView.DrawToolbarButton (UnityEngine.GUIContent guiContent, System.Action onClick) (at Library/PackageCache/com.unity.project-auditor@c73131f0c1/Editor/UI/Framework/AnalysisView.cs:576)

2022-10-04 12:02 UTC, mtrive commented
> As discussed, I think ShaderTypeIsFragment() needs a comment explaining the context around why it does what it does with OpenGL/ES shaders. 

Good point. Added a comment.

> More seriously, I'm seeing a divide by 0 exception on line 411 of ShadersModule.cs. I guess (numCompilerPlatforms == 0) for some shaders? Error message and partial callstack below. Repro steps are:
> 
> * Add this branch of PA to a new project with the LEGO Microgame, 2021.3.7f1
> * Open Project Auditor, go to Shader Variants window, click Clear
> * Build the game (I build OSX Standalone)
> * In the Shader Variants window, click Refresh.
> 
> DivideByZeroException: Attempted to divide by zero. Unity.ProjectAuditor.Editor.Modules.ShadersModule.AddShader 

Fixed.

2022-10-04 14:33 UTC, unitystevem approved these changes

2022-10-04 15:23 UTC, merged